name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
        node-version: '12'
      - run: npm i
      - run: npm lint
      - run: npm test